const fetchFetchCustomerHistory = () => {
  // Example transaction history data
  const CustomerHistory = [
    {
      id: 1,
      customer_id: "uc12",
      accountType: [
        { Name: "Savings" },
        { Name: "Business" },
        { Name: "Master_POS" },
        { Name: "Sub_POS" },
      ],
      firstName: "Mirabel",
      middleName: "Nne",
      lastName: "Ifunanya",
      surname: "Benjamin",
      address: [
        { AddressLineOne: "20a cowley road" },
        { City: "Uxbridge" },
        { State: "Middle sex" },
        { PostCode: "UBG123" },
        { Country: "United Kingdom" },
      ],
      password: "12345abcd",
      passcode: "123456",
      countryCode: "+123",
      phoneNumber: [
        { Default: "07023467889", Provider: "MTN" },
        { Altanative: "0824567869", Provider: "Airtel" },
      ],
      email: "Benjaminchinwike@gmail.com",
      pictureURL: "URL",
      counttryFlagURL: "URL",
      governmentIssuedIdNumber: [
        { NIN: "1222567890", imageURL: "URL" },
        { BVN: "12345678", ImageURL: "URL" },
      ],
      status: "upcoming",
    },
    {
      id: 1,
      customer_id: "uc14",
      accountType: [
        { Name: "Savings" },
        { Name: "Business" },
        { Name: "Master_POS" },
        { Name: "Sub_POS" },
      ],
      firstName: "Mirabel",
      middleName: "Nne",
      lastName: "Ifunanya",
      surname: "Benjamin",
      address: [
        { AddressLineOne: "20a cowley road" },
        { City: "Uxbridge" },
        { State: "Middle sex" },
        { PostCode: "UBG123" },
        { Country: "United Kingdom" },
      ],
      password: "12345abcd",
      passcode: "123456",
      countryCode: "+123",
      phoneNumber: [
        { Default: "07023467889", Provider: "MTN" },
        { Altanative: "0824567869", Provider: "Airtel" },
      ],
      email: "Benjaminchinwike@gmail.com",
      pictureURL: "URL",
      counttryFlagURL: "URL",
      governmentIssuedIdNumber: [
        { NIN: "1222567890", imageURL: "URL" },
        { BVN: "12345678", ImageURL: "URL" },
      ],
      status: "upcoming",
    },
    {
      id: 1,
      customer_id: "uc17",
      accountType: [
        { Name: "Savings" },
        { Name: "Business" },
        { Name: "Master_POS" },
        { Name: "Sub_POS" },
      ],
      firstName: "Mirabel",
      middleName: "Nne",
      lastName: "Ifunanya",
      surname: "Benjamin",
      address: [
        { AddressLineOne: "20a cowley road" },
        { City: "Uxbridge" },
        { State: "Middle sex" },
        { PostCode: "UBG123" },
        { Country: "United Kingdom" },
      ],
      password: "12345abcd",
      passcode: "123456",
      countryCode: "+123",
      phoneNumber: [
        { Default: "07023467889", Provider: "MTN" },
        { Altanative: "0824567869", Provider: "Airtel" },
      ],
      email: "Benjaminchinwike@gmail.com",
      pictureURL: "URL",
      counttryFlagURL: "URL",
      governmentIssuedIdNumber: [
        { NIN: "1222567890", imageURL: "URL" },
        { BVN: "12345678", ImageURL: "URL" },
      ],
      status: "upcoming",
    },
    {
      id: 1,
      customer_id: "uc13",
      accountType: [
        { Name: "Savings" },
        { Name: "Business" },
        { Name: "Master_POS" },
        { Name: "Sub_POS" },
      ],
      firstName: "Mikel",
      middleName: "Chibugo",
      lastName: "Mikel",
      surname: "Benjamin",
      address: [
        { AddressLineOne: "20a cowley road" },
        { City: "Uxbridge" },
        { State: "Middle sex" },
        { PostCode: "UBG123" },
        { Country: "United Kingdom" },
      ],
      password: "12345abcd",
      Passcode: "123456",
      countryCode: "+123",
      PhoneNumber: [
        { Default: "07023467889", Provider: "MTN" },
        { Altanative: "0824567869", Provider: "Airtel" },
      ],
      email: "Benjaminchinwike@gmail.com",
      pictureURL: "URL",
      counttryFlagURL: "URL",
      governmentIssuedIdNumber: [
        { NIN: "1222567890", imageURL: "URL" },
        { BVN: "12345678", ImageURL: "URL" },
      ],
      status: "upcoming",
    },
  ];

  return CustomerHistory;
};

export default fetchFetchCustomerHistory;
