export { default as AddDevice } from './AddDevice/AddDevice'
export { default as AddPaymentMethod2 } from './AddPaymentMethod2/AddPaymentMethod2'
export { default as AgupePay } from './AgupePay/AgupePay'
export { default as Analytics2 } from './Analytics2/Analytics2'
export { default as Authentication2 } from './Authentication2/Authentication2'
export { default as Calculator } from './Calculator/Calculator'
export { default as Details } from './Details2/Details2'
export { default as ItemsGallery } from './ItemsGallery/ItemsGallery'
export { default as LoginPay } from './LoginPay/LoginPay'
export { default as MakePayment } from './MakePayment/MakePayment'
export { default as ReivePayment } from './ReceivePayment/ReceivePayment'
export { default as Sell } from './Sell/Sell'
export { default as Settings2 } from './Settings2/Settings2'
export { default as Statement2 } from './Statement2/Statement2'
export { default as Theme2 } from './Theme2/Theme2'
export { default as TransactionCategory2 } from './TransactionCategory2/TransactionCategory2'
export { default as Transactions2 } from './Transactions2/Transactions2'
export { default as Withdraw2 } from './Withdraw2/Withdraw2'
export { default as Personal2 } from './Personal2/Personal2'
export { default as Business2 } from './Business2/Business2'



